module.exports = {
  html: 'page',
  md: 'page',
  mdown: 'page',
  markdown: 'page',
  handlebars: 'page',
  hbs: 'page',
  njk: 'page',
  nunjucks: 'page',
  nunjs: 'page',
  nunj: 'page',
  njs: 'page',
  njx: 'page',
  j2: 'page',

  js: 'script',
  es6: 'script',
  es: 'script',
  jsx: 'script',

  css: 'stylesheet',
  less: 'stylesheet',
  sass: 'stylesheet',
  scss: 'stylesheet',
  styl: 'stylesheet',

  jpeg: 'image',
  jpg: 'image',
  svg: 'image',
  png: 'image',
  gif: 'image',

  json: 'datafile',
  yml: 'datafile',
  yaml: 'datafile',
}
